@startuml Communication_Presence_Campus
skinparam defaultFontName Arial
skinparam shadowing false
skinparam dpi 150
left to right direction

actor "Charge Transport" as CT
rectangle "Web UI" as UI
rectangle "PresenceController" as PreC
rectangle "PresenceService" as PreS
database "DB" as DB

CT -[#black]-> UI : 1: saisir présence(date, arrivés, partis, présents)
UI -[#black]-> PreC : 2: POST /presence
PreC -[#black]-> PreS : 3: valider_presence(data)
PreS -[#black]-> DB : 3.1: insert(presence_campus)
DB -[#black]-> PreS : 3.2: id
PreS -[#black]-> PreC : 3.3: ok
PreC -[#black]-> UI : 4: confirmation
UI -[#black]-> CT : 5: affiche récapitulatif

@enduml
