@startuml Communication_Panne_Depannage
skinparam defaultFontName Arial
skinparam shadowing false
skinparam dpi 150
left to right direction

actor "Mécanicien" as MEC
actor "Chauffeur" as CH
rectangle "Web UI" as UI
rectangle "PanneController" as PanC
rectangle "DepannageController" as DepC
rectangle "PanneService" as PanS
rectangle "DepannageService" as DepS
rectangle "NotificationService" as Notif
database "DB" as DB

CH -[#black]-> UI : 1: signaler panne(bus, criticité, desc)
UI -[#black]-> PanC : 2: POST /panne
PanC -[#black]-> PanS : 3: valider_panne(data)
PanS -[#black]-> DB : 3.1: insert(panne)
DB -[#black]-> PanS : 3.2: id
PanS -[#black]-> Notif : 3.3: notifier(equipe)
PanC -[#black]-> UI : 4: confirmation

MEC -[#black]-> UI : 5: planifier/enregistrer dépannage(panne)
UI -[#black]-> DepC : 6: POST /depannage
DepC -[#black]-> DB : 6.1: insert(depannage)
DB -[#black]-> DepC : 6.2: id
DepC -[#black]-> DB : 7: update(panne.resolue=true)
DB -[#black]-> DepC : 7.1: OK
DepC -[#black]-> Notif : 8: notifier(résolution)
DepC -[#black]-> UI : 9: confirmation

@enduml
