@startuml Communication_Gestion_Vehicules_Docs
skinparam defaultFontName Arial
skinparam shadowing false
skinparam dpi 150
left to right direction

actor "Administrateur" as ADM
rectangle "Web UI" as UI
rectangle "BusController" as BusC
rectangle "DocumentController" as DocC
rectangle "BusService" as BusS
rectangle "DocumentService" as DocS
database "DB" as DB

ADM -[#black]-> UI : 1: créer/modifier/supprimer véhicule
UI -[#black]-> BusC : 2: action véhicule
BusC -[#black]-> BusS : 3: valider_et_persister(data)
BusS -[#black]-> DB : 3.1: insert/update/delete(bus)
DB -[#black]-> BusS : 3.2: OK
BusS -[#black]-> BusC : 3.3: résultat
BusC -[#black]-> UI : 4: confirmation

ADM -[#black]-> UI : 5: gérer documents
UI -[#black]-> DocC : 6: POST /document_bus
DocC -[#black]-> DocS : 7: controler_type_document()
DocS -[#black]-> DB : 7.1: insert(doc)
DB -[#black]-> DocS : 7.2: id
DocS -[#black]-> DocC : 7.3: ok
DocC -[#black]-> UI : 8: confirmation

@enduml
